# Generated by Django 2.0.6 on 2019-07-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('thn_produksi', models.CharField(max_length=100)),
                ('cc_mototr', models.CharField(max_length=100)),
            ],
        ),
    ]
